name: hello world

# trigger
on: 
- push

# one or more jobs
jobs: 
    greetings: 
        runs-on: ubuntu-latest
        steps: 
        - id: s01
          run: echo "current time in Github is $(date)"

        - id: s02
          run: cat hello.txt